# TCL File Generated by Component Editor 18.1
# Mon Jan 31 15:26:45 IRKT 2022
# DO NOT MODIFY


# 
# generator "gen" v1.0
#  2022.01.31.15:26:45
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module generator
# 
set_module_property DESCRIPTION ""
set_module_property NAME generator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME gen
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL gen
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gen.v VERILOG PATH gen.v TOP_LEVEL_FILE
add_fileset_file sdmodb.v VERILOG PATH sdmodb.v
add_fileset_file sine_rom.v VERILOG PATH sine_rom.v
add_fileset_file sine_rom_syn.v VERILOG PATH sine_rom_syn.v
add_fileset_file sine256.mif MIF PATH sine256.mif
add_fileset_file phacc.v VERILOG PATH phacc.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL gen
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gen.v VERILOG PATH gen.v
add_fileset_file sdmodb.v VERILOG PATH sdmodb.v
add_fileset_file sine_rom.v VERILOG PATH sine_rom.v
add_fileset_file sine_rom_syn.v VERILOG PATH sine_rom_syn.v
add_fileset_file sine256.mif MIF PATH sine256.mif
add_fileset_file phacc.v VERILOG PATH phacc.v


# 
# parameters
# 
add_parameter PHACC_WIDTH INTEGER 14
set_parameter_property PHACC_WIDTH DEFAULT_VALUE 14
set_parameter_property PHACC_WIDTH DISPLAY_NAME PHACC_WIDTH
set_parameter_property PHACC_WIDTH TYPE INTEGER
set_parameter_property PHACC_WIDTH UNITS None
set_parameter_property PHACC_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PHACC_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clr_n
# 
add_interface clr_n reset end
set_interface_property clr_n associatedClock clk
set_interface_property clr_n synchronousEdges DEASSERT
set_interface_property clr_n ENABLED true
set_interface_property clr_n EXPORT_OF ""
set_interface_property clr_n PORT_NAME_MAP ""
set_interface_property clr_n CMSIS_SVD_VARIABLES ""
set_interface_property clr_n SVD_ADDRESS_GROUP ""

add_interface_port clr_n clr_n reset_n Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clk
set_interface_property avalon_slave associatedReset clr_n
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave wr_data writedata Input 32
add_interface_port avalon_slave wr_n write_n Input 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point dacout
# 
add_interface dacout conduit end
set_interface_property dacout associatedClock clk
set_interface_property dacout associatedReset clr_n
set_interface_property dacout ENABLED true
set_interface_property dacout EXPORT_OF ""
set_interface_property dacout PORT_NAME_MAP ""
set_interface_property dacout CMSIS_SVD_VARIABLES ""
set_interface_property dacout SVD_ADDRESS_GROUP ""

add_interface_port dacout fout fout Output 1

